---
ID: "e20e2c4d-6fcd-40a6-a617-32d33cee084c"
Parent: "f918f4db-fffc-4ee4-bac7-3fd64d68ef4c"
Template: "f918f4db-fffc-4ee4-bac7-3fd64d68ef4c"
Path: "/sitecore/templates/Project/SUGCON2023-GoHorse/Page/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {F918F4DB-FFFC-4EE4-BAC7-3FD64D68EF4C}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230908T001901Z
    - ID: "48924be3-bcb7-49f5-a38c-765478a53803"
      Hint: Title
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rpeplau@arke.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rpeplau@arke.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6de2dacc-b013-47d4-80cd-9158b1b9b574"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rpeplau@arke.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230908T001907Z
